#!/usr/bin/php
<?php

$cfgFileContent = "<?php\n";

if(getenv("BLOWFISH_SECRET") != "") {
	$cfgFileContent .= sprintf("\$cfg['blowfish_secret'] = \"%s\";\n", getenv("BLOWFISH_SECRET"));
}

$serverConfOptions = ['host', 'port', 'pmadb', 'controlhost', 'controlport', 'controluser', 'controlpass'];


for($i=1; $i<=10; $i++) {
	foreach($serverConfOptions as $option) {
		$envKey = sprintf("SERVER_%u_%s", $i, strtoupper($option));

		if(getenv($envKey)!="") {
			$cfgFileContent .= sprintf("\$cfg['Servers'][%u]['%s'] = \"%s\";\n", $i, $option, getenv($envKey));
		}
	}
}

file_put_contents("/var/www/config.inc.php", $cfgFileContent);

array_shift($argv);
pcntl_exec(array_shift($argv), $argv);
