#!/usr/bin/php
<?php

$cfgFileContent = "<?php\n";

$configMappings = [
	'PMA_ABSOLUTE_URI' => 'PmaAbsoluteUri',
	'BLOWFISH_SECRET'  => 'blowfish_secret'
];

foreach($configMappings as $env => $mapping) {
	if(getenv($env) != "") {
		$cfgFileContent .= sprintf("\$cfg['%s'] = \"%s\";\n", $mapping, getenv($env));
	}
}

$serverConfOptions = ['host', 'port', 'auth_type', 'pmadb', 'controlhost', 'controlport', 'controluser', 'controlpass'];

for($i=1; $i<=10; $i++) {
	foreach($serverConfOptions as $option) {
		$envKey = sprintf("SERVER_%u_%s", $i, strtoupper($option));

		if(getenv($envKey)!="") {
			$cfgFileContent .= sprintf("\$cfg['Servers'][%u]['%s'] = \"%s\";\n", $i, $option, getenv($envKey));
		}
	}
}

file_put_contents("/var/www/config.inc.php", $cfgFileContent);

array_shift($argv);
pcntl_exec(array_shift($argv), $argv);
